import { AUDIT_ENTITY_TYPES } from '../audit/audit.constants';

/**
 * Finance-domain audit entity types exposed via GET /finance/audit.
 * Global audit still covers all domains; this set is the Finance filter boundary.
 */
export const FINANCE_AUDIT_ENTITY_TYPES = [
  AUDIT_ENTITY_TYPES.FINANCIAL_ACCOUNT,
  AUDIT_ENTITY_TYPES.FINANCIAL_ACCOUNT_MOVEMENT,
  AUDIT_ENTITY_TYPES.FINANCIAL_ACCOUNT_TRANSFER,
  AUDIT_ENTITY_TYPES.CAPITAL_CONTRIBUTION,
  AUDIT_ENTITY_TYPES.LOAN,
  AUDIT_ENTITY_TYPES.LOAN_DISBURSEMENT,
  AUDIT_ENTITY_TYPES.LOAN_REPAYMENT,
  AUDIT_ENTITY_TYPES.SUPPLIER_PAYABLE,
  AUDIT_ENTITY_TYPES.SUPPLIER_CREDIT,
  AUDIT_ENTITY_TYPES.SUPPLIER_PAYMENT_ALLOCATION,
  AUDIT_ENTITY_TYPES.FX_RATE,
  AUDIT_ENTITY_TYPES.FX_CONVERSION,
  AUDIT_ENTITY_TYPES.PAYMENT,
  AUDIT_ENTITY_TYPES.RECEIPT,
  AUDIT_ENTITY_TYPES.EXPENSE_CATEGORY,
  AUDIT_ENTITY_TYPES.EXPENSE,
  AUDIT_ENTITY_TYPES.EXPENSE_PAYMENT_ALLOCATION,
  AUDIT_ENTITY_TYPES.PURCHASE_COST_ALLOCATION_LINE,
  AUDIT_ENTITY_TYPES.INVENTORY_COST_COMPONENT,
  AUDIT_ENTITY_TYPES.LEDGER_ACCOUNT,
  AUDIT_ENTITY_TYPES.JOURNAL_ENTRY,
] as const;

export type FinanceAuditEntityType = (typeof FINANCE_AUDIT_ENTITY_TYPES)[number];

export const FINANCE_AUDIT_ENTITY_TYPE_SET = new Set<string>(FINANCE_AUDIT_ENTITY_TYPES);

export function isFinanceAuditEntityType(value: string): value is FinanceAuditEntityType {
  return FINANCE_AUDIT_ENTITY_TYPE_SET.has(value);
}
