/** Human-friendly Persian labels for common Finance audit actions. */
export const FINANCE_AUDIT_ACTION_LABELS: Record<string, string> = {
  FINANCIAL_ACCOUNT_CREATED: 'ایجاد حساب مالی',
  FINANCIAL_ACCOUNT_UPDATED: 'ویرایش حساب مالی',
  FINANCIAL_ACCOUNT_ARCHIVED: 'بایگانی حساب مالی',
  FINANCIAL_ACCOUNT_ACTIVATED: 'فعال‌سازی حساب',
  FINANCIAL_ACCOUNT_DEACTIVATED: 'غیرفعال‌سازی حساب',
  FINANCIAL_ACCOUNT_DEFAULT_CHANGED: 'تغییر حساب پیش‌فرض',
  OPENING_BALANCE_RECORDED: 'ثبت موجودی افتتاحیه',
  ACCOUNT_TRANSFER_CREATED: 'ایجاد انتقال',
  ACCOUNT_TRANSFER_POSTED: 'ثبت انتقال',
  ACCOUNT_TRANSFER_CANCELLED: 'لغو انتقال',
  ACCOUNT_TRANSFER_REVERSED: 'برگشت انتقال',
  CAPITAL_CONTRIBUTION_CREATED: 'ایجاد آورده سرمایه',
  CAPITAL_CONTRIBUTION_POSTED: 'ثبت آورده سرمایه',
  CAPITAL_CONTRIBUTION_REVERSED: 'برگشت آورده سرمایه',
  LOAN_CREATED: 'ایجاد وام',
  LOAN_UPDATED: 'ویرایش وام',
  LOAN_DISBURSEMENT_POSTED: 'ثبت دریافت اصل وام',
  LOAN_REPAYMENT_POSTED: 'ثبت بازپرداخت وام',
  LOAN_SETTLED: 'تسویه وام',
  SUPPLIER_PAYABLE_RECOGNIZED: 'شناخت بدهی تأمین‌کننده',
  SUPPLIER_PAYABLE_OPENING_RECORDED: 'ثبت بدهی افتتاحیه',
  SUPPLIER_PAYABLE_ADJUSTED: 'تعدیل بدهی تأمین‌کننده',
  SUPPLIER_PAYABLE_SETTLEMENT_POSTED: 'ثبت تسویه بدهی',
  SUPPLIER_PAYABLE_SETTLEMENT_REVERSED: 'برگشت تسویه بدهی',
  SUPPLIER_PAYABLE_ALLOCATION_POSTED: 'تخصیص پرداخت به بدهی',
  SUPPLIER_CREDIT_CREATED: 'ایجاد اعتبار تأمین‌کننده',
  PAYMENT_CREATED: 'ایجاد پرداخت',
  PAYMENT_POSTED: 'ثبت پرداخت',
  PAYMENT_CANCELLED: 'لغو پرداخت',
  PAYMENT_REVERSED: 'برگشت پرداخت',
  RECEIPT_CREATED: 'ایجاد دریافت',
  RECEIPT_POSTED: 'ثبت دریافت',
  RECEIPT_CANCELLED: 'لغو دریافت',
  RECEIPT_REVERSED: 'برگشت دریافت',
  EXPENSE_CATEGORY_CREATED: 'ایجاد دسته هزینه',
  EXPENSE_CATEGORY_ARCHIVED: 'بایگانی دسته هزینه',
  EXPENSE_CREATED: 'ایجاد هزینه',
  EXPENSE_UPDATED: 'ویرایش هزینه',
  EXPENSE_APPROVED: 'تأیید هزینه',
  EXPENSE_CANCELLED: 'لغو هزینه',
  EXPENSE_PAYMENT_ALLOCATED: 'تخصیص پرداخت به هزینه',
  FX_RATE_CREATED: 'ثبت نرخ ارز',
  FX_RATE_ARCHIVED: 'بایگانی نرخ ارز',
  FX_CONVERSION_CREATED: 'ایجاد تبدیل ارز',
  FX_CONVERSION_POSTED: 'ثبت تبدیل ارز',
  FX_CONVERSION_REVERSED: 'برگشت تبدیل ارز',
  JOURNAL_CREATED: 'ایجاد سند روزنامه',
  JOURNAL_POSTED: 'ثبت سند روزنامه',
  JOURNAL_REVERSED: 'برگشت سند روزنامه',
  LEDGER_ACCOUNT_CREATED: 'ایجاد حساب دفتر',
  LEDGER_ACCOUNT_ARCHIVED: 'بایگانی حساب دفتر',
  PURCHASE_COST_TREATMENT_SET: 'تعیین رفتار هزینه خرید',
  PURCHASE_COST_ALLOCATED: 'تخصیص هزینه خرید',
  PURCHASE_COST_CAPITALIZED: 'سرمایه‌گذاری هزینه خرید',
};

export const FINANCE_AUDIT_ENTITY_TYPE_LABELS: Record<string, string> = {
  FINANCIAL_ACCOUNT: 'حساب مالی',
  FINANCIAL_ACCOUNT_MOVEMENT: 'حرکت حساب',
  FINANCIAL_ACCOUNT_TRANSFER: 'انتقال بین حساب‌ها',
  CAPITAL_CONTRIBUTION: 'آورده سرمایه',
  LOAN: 'وام',
  LOAN_DISBURSEMENT: 'دریافت وام',
  LOAN_REPAYMENT: 'بازپرداخت وام',
  SUPPLIER_PAYABLE: 'بدهی تأمین‌کننده',
  SUPPLIER_CREDIT: 'اعتبار تأمین‌کننده',
  SUPPLIER_PAYMENT_ALLOCATION: 'تسویه بدهی تأمین‌کننده',
  FX_RATE: 'نرخ ارز',
  FX_CONVERSION: 'تبدیل ارز',
  PAYMENT: 'پرداخت',
  RECEIPT: 'دریافت',
  EXPENSE_CATEGORY: 'دسته هزینه',
  EXPENSE: 'هزینه',
  EXPENSE_PAYMENT_ALLOCATION: 'تخصیص پرداخت هزینه',
  PURCHASE_COST_ALLOCATION_LINE: 'قلم تخصیص هزینه خرید',
  INVENTORY_COST_COMPONENT: 'جزء بهای موجودی',
  LEDGER_ACCOUNT: 'حساب دفتر',
  JOURNAL_ENTRY: 'سند روزنامه',
};

export const FINANCE_AUDIT_ENTITY_TYPE_OPTIONS = Object.keys(FINANCE_AUDIT_ENTITY_TYPE_LABELS);

export function financeAuditActionLabel(action: string): string {
  return FINANCE_AUDIT_ACTION_LABELS[action] ?? action;
}

export function financeAuditEntityTypeLabel(entityType: string): string {
  return FINANCE_AUDIT_ENTITY_TYPE_LABELS[entityType] ?? entityType;
}
