import { isApiClientError } from '@/lib/api/errors';

const BUSINESS_MESSAGES: Record<string, string> = {
  LAST_OWNER_REQUIRED:
    'شرکت باید حداقل یک مالک فعال داشته باشد. قبل از حذف یا تغییر دسترسی این عضو، مالک دیگری تعیین کنید.',
  ROLE_PERMISSION_ESCALATION:
    'نمی‌توانید دسترسی‌ای بالاتر از سطح دسترسی خودتان واگذار کنید.',
  ROLE_SYSTEM_PROTECTED: 'این نقش توسط سیستم مدیریت می‌شود و قابل تغییر یا حذف نیست.',
  ROLE_IN_USE: 'این نقش به اعضای فعال تخصیص داده شده و قابل حذف نیست.',
  ROLE_ALREADY_EXISTS: 'کلید نقش تکراری است.',
  ROLE_NOT_FOUND: 'نقش مورد نظر پیدا نشد.',
  MEMBER_NOT_FOUND: 'عضو مورد نظر پیدا نشد.',
  MEMBERSHIP_ALREADY_EXISTS: 'این کاربر هم‌اکنون عضو شرکت است.',
  MEMBERSHIP_SUSPENDED: 'عضویت این کاربر تعلیق شده است.',
  MEMBERSHIP_REMOVED: 'عضویت این کاربر حذف شده است.',
  USER_NOT_FOUND: 'کاربری با این ایمیل پیدا نشد.',
  COMPANY_NOT_FOUND: 'شرکت مورد نظر پیدا نشد.',
  COMPANY_UNAVAILABLE: 'شرکت در دسترس نیست.',
  PERMISSION_REQUIRED: 'شما دسترسی لازم برای این عملیات را ندارید.',
  FORBIDDEN: 'شما دسترسی لازم برای این عملیات را ندارید.',
  NOT_FOUND: 'مورد درخواستی پیدا نشد.',
  INVALID_ROLE_ASSIGNMENT: 'تخصیص نقش نامعتبر است.',
  INVALID_COMPANY_ROLE: 'نقش انتخاب‌شده برای این شرکت معتبر نیست.',
  PERMISSION_NOT_FOUND: 'یکی از دسترسی‌های انتخاب‌شده معتبر نیست.',
  BRAND_NOT_FOUND: 'برند مورد نظر پیدا نشد.',
  BRAND_NAME_ALREADY_EXISTS: 'برندی با این نام در شرکت وجود دارد.',
  BRAND_CODE_ALREADY_EXISTS: 'کد برند تکراری است.',
  CATEGORY_NOT_FOUND: 'دسته‌بندی مورد نظر پیدا نشد.',
  CATEGORY_NAME_ALREADY_EXISTS: 'دسته‌بندی با این نام در همین سطح وجود دارد.',
  CATEGORY_CODE_ALREADY_EXISTS: 'کد دسته‌بندی تکراری است.',
  CATEGORY_CYCLE_DETECTED: 'انتقال این دسته‌بندی باعث ایجاد حلقه در درخت می‌شود.',
  CATEGORY_CROSS_COMPANY_PARENT: 'دسته‌بندی والد متعلق به این شرکت نیست.',
  CATEGORY_DEPTH_EXCEEDED: 'عمق درخت دسته‌بندی از حد مجاز بیشتر است.',
  CATALOG_ITEM_ARCHIVED: 'این مورد بایگانی شده و قابل این عملیات نیست.',
  PRODUCT_NOT_FOUND: 'محصول مورد نظر پیدا نشد.',
  PRODUCT_NOT_ACTIVE: 'برای این عملیات، محصول باید فعال باشد.',
  SKU_NOT_FOUND: 'SKU مورد نظر پیدا نشد.',
  SKU_CODE_ALREADY_EXISTS: 'کد SKU تکراری است (کد SKUهای بایگانی‌شده نیز رزرو می‌ماند).',
  SKU_VARIANT_ALREADY_EXISTS: 'SKU دیگری با همین ترکیب تنوع برای این محصول وجود دارد.',
  SKU_SIMPLE_LIMIT: 'محصول بدون ویژگی تنوع فقط می‌تواند یک SKU داشته باشد.',
  SKU_VARIANT_INCOMPLETE: 'برای هر ویژگی تنوع دقیقاً یک مقدار انتخاب کنید.',
  SKU_VARIANT_DUPLICATE_OPTION: 'برای یک ویژگی نمی‌توان چند مقدار انتخاب کرد.',
  SKU_VARIANT_VALUE_NOT_FOUND: 'مقدار انتخاب‌شده برای این محصول معتبر نیست.',
  SKU_VARIANT_VALUE_INACTIVE: 'مقدار غیرفعال را نمی‌توان برای SKU جدید انتخاب کرد.',
  SKU_ALREADY_ARCHIVED: 'این SKU بایگانی شده است.',
  SKU_ACTIVATION_BLOCKED: 'برای فعال‌سازی SKU، محصول باید فعال و انتخاب تنوع معتبر باشد.',
  VARIANT_OPTION_NOT_FOUND: 'ویژگی تنوع پیدا نشد.',
  VARIANT_OPTION_NAME_EXISTS: 'ویژگی تنوعی با این نام برای محصول وجود دارد.',
  VARIANT_OPTION_ADD_BLOCKED:
    'پس از ایجاد SKU، افزودن ویژگی تنوع جدید ممکن نیست.',
  VARIANT_VALUE_NOT_FOUND: 'مقدار ویژگی پیدا نشد.',
  VARIANT_VALUE_EXISTS: 'این مقدار قبلاً برای ویژگی ثبت شده است.',
  BULK_SKU_LIMIT_EXCEEDED: 'تعداد SKUها در ایجاد گروهی از سقف مجاز بیشتر است.',
  BULK_SKU_DUPLICATE_IN_REQUEST: 'درخواست شامل کد یا ترکیب تکراری است.',
  BARCODE_NOT_FOUND: 'بارکد پیدا نشد.',
  BARCODE_NOT_ACTIVE: 'این بارکد آرشیو شده است.',
  BARCODE_INVALID: 'مقدار بارکد برای نوع انتخاب‌شده معتبر نیست.',
  BARCODE_INVALID_CHECKSUM: 'رقم کنترلی بارکد نامعتبر است.',
  BARCODE_ALREADY_EXISTS: 'این بارکد قبلاً در شرکت ثبت شده است.',
  BARCODE_ALREADY_ARCHIVED: 'این بارکد قبلاً آرشیو شده است.',
  INTERNAL_BARCODE_ALREADY_EXISTS: 'این SKU هم‌اکنون یک بارکد داخلی فعال دارد.',
  PRIMARY_BARCODE_CONFLICT: 'هر SKU فقط می‌تواند یک بارکد اصلی فعال داشته باشد.',
  SUPPLIER_NOT_FOUND: 'تأمین‌کننده مورد نظر پیدا نشد.',
  SUPPLIER_CODE_ALREADY_EXISTS: 'کد تأمین‌کننده تکراری است.',
  SUPPLIER_CONTACT_NOT_FOUND: 'مخاطب تأمین‌کننده پیدا نشد.',
  SUPPLIER_CONTACT_ALREADY_ARCHIVED: 'این مخاطب قبلاً بایگانی شده است.',
  SUPPLIER_PRIMARY_CONTACT_CONFLICT: 'مخاطب اصلی دیگری برای این تأمین‌کننده ثبت شده است.',
  SUPPLIER_NOTE_NOT_FOUND: 'یادداشت پیدا نشد.',
  SUPPLIER_INVALID_STATUS_TRANSITION: 'تغییر وضعیت تأمین‌کننده مجاز نیست.',
  SUPPLIER_INACTIVE: 'این تأمین‌کننده غیرفعال است.',
  INVALID_SUPPLIER_NAME: 'نام تأمین‌کننده نامعتبر است.',
  INVALID_SUPPLIER_CODE: 'کد تأمین‌کننده نامعتبر است.',
  INVALID_SUPPLIER_EMAIL: 'ایمیل تأمین‌کننده نامعتبر است.',
  INVALID_CONTACT_NAME: 'نام مخاطب نامعتبر است.',
  INVALID_NOTE_BODY: 'متن یادداشت نامعتبر است.',
  SUPPLIER_OFFER_NOT_FOUND: 'استعلام قیمت پیدا نشد.',
  SUPPLIER_OFFER_ALREADY_ARCHIVED: 'این استعلام قبلاً بایگانی شده است.',
  SUPPLIER_OFFER_SUPPLIER_NOT_ASSIGNABLE:
    'فقط برای تأمین‌کننده فعال یا غیرفعال (نه بایگانی) می‌توان قیمت ثبت کرد.',
  SUPPLIER_OFFER_SKU_NOT_ASSIGNABLE: 'فقط برای SKU غیر بایگانی می‌توان قیمت ثبت کرد.',
  SUPPLIER_OFFER_CONTACT_INVALID: 'مخاطب انتخاب‌شده متعلق به این تأمین‌کننده نیست.',
  SUPPLIER_OFFER_INVALID_TERMS: 'نوع خرید و شرایط پرداخت با هم سازگار نیستند.',
  SUPPLIER_OFFER_INVALID_FX: 'نرخ ارز مرجع نیاز به جفت ارز و مقدار مثبت دارد.',
  SUPPLIER_OFFER_INVALID_PRICE: 'قیمت واحد باید مقدار مثبت باشد.',
  SUPPLIER_OFFER_INVALID_VALIDITY: 'تاریخ انقضا باید بعد از تاریخ استعلام باشد.',
  PURCHASE_ORDER_NOT_FOUND: 'سفارش خرید پیدا نشد.',
  PURCHASE_ORDER_ITEM_NOT_FOUND: 'قلم سفارش خرید پیدا نشد.',
  PURCHASE_ORDER_INVALID_STATUS_TRANSITION: 'تغییر وضعیت سفارش خرید مجاز نیست.',
  PURCHASE_ORDER_NOT_EDITABLE: 'این سفارش در وضعیت فعلی قابل ویرایش نیست.',
  PURCHASE_ORDER_VERSION_CONFLICT:
    'سفارش توسط کاربر دیگری تغییر کرده است. صفحه را تازه‌سازی کنید.',
  PURCHASE_ORDER_DUPLICATE_SKU: 'هر SKU فقط یک‌بار در یک سفارش قابل ثبت است.',
  PURCHASE_ORDER_EMPTY: 'برای این عملیات حداقل یک قلم کالا لازم است.',
  PURCHASE_ORDER_PARTY_LOCKED:
    'تا وقتی قلم کالا وجود دارد، تأمین‌کننده یا ارز قابل تغییر نیست.',
  PURCHASE_ORDER_SUPPLIER_NOT_ASSIGNABLE:
    'فقط تأمین‌کننده فعال یا غیرفعال (نه بایگانی) قابل انتخاب است.',
  PURCHASE_ORDER_SKU_NOT_ASSIGNABLE: 'فقط SKU غیر بایگانی قابل افزودن به سفارش است.',
  PURCHASE_ORDER_CONTACT_INVALID: 'مخاطب انتخاب‌شده متعلق به این تأمین‌کننده نیست.',
  PURCHASE_ORDER_OFFER_INVALID: 'استعلام قیمت انتخاب‌شده با سفارش یا SKU سازگار نیست.',
  PURCHASE_ORDER_INVALID_QUANTITY: 'تعداد باید عدد صحیح مثبت باشد.',
  PURCHASE_ORDER_INVALID_PRICE: 'قیمت واحد باید مقدار مثبت معتبر باشد.',
  PURCHASE_ORDER_INVALID_DATES: 'تاریخ‌های سفارش نامعتبر است.',
  PURCHASE_ORDER_TOTAL_OUT_OF_RANGE: 'مبلغ کل سفارش از محدوده مجاز خارج است.',
  PURCHASE_ORDER_INVALID_TERMS: 'نوع خرید و شرایط تجاری با هم سازگار نیستند.',
  PURCHASE_ORDER_INVALID_FX: 'برای خرید ارزی، نرخ مرجع و جفت ارز الزامی است.',
  PURCHASE_ORDER_TERMS_INCOMPLETE: 'شرایط تجاری نوع خرید برای این مرحله کامل نیست.',
  PURCHASE_CORRECTION_NOT_ALLOWED:
    'در وضعیت فعلی این خرید، اصلاح تجاری مجاز نیست. برای پیش‌نویس از ویرایش عادی استفاده کنید.',
  PURCHASE_CORRECTION_UNSUPPORTED: 'این نوع اصلاح پشتیبانی نمی‌شود.',
  PURCHASE_CORRECTION_REASON_REQUIRED: 'دلیل اصلاح الزامی است.',
  PURCHASE_SHORT_CLOSE_INVALID: 'مقدار بستن کسری نامعتبر است.',
  PURCHASE_SHORT_CLOSE_NOT_ALLOWED: 'بستن مقدار تأمین‌نشده در این وضعیت مجاز نیست.',
  PURCHASE_DISCREPANCY_INVALID: 'مغایرت خرید نامعتبر است.',
  PURCHASE_RETURN_NOT_FOUND: 'برگشت به تأمین‌کننده پیدا نشد.',
  PURCHASE_RETURN_INVALID_STATUS: 'تغییر وضعیت برگشت مجاز نیست.',
  PURCHASE_RETURN_EMPTY: 'برگشت باید حداقل یک قلم داشته باشد.',
  PURCHASE_RETURN_SUPPLIER_MISMATCH: 'تأمین‌کننده برگشت باید با سفارش خرید یکی باشد.',
  PURCHASE_RETURN_ITEM_INVALID: 'قلم برگشت متعلق به این سفارش نیست.',
  PURCHASE_RETURN_SKU_MISMATCH: 'SKU قلم برگشت با سفارش خرید سازگار نیست.',
  PURCHASE_RETURN_VERSION_CONFLICT:
    'برگشت توسط کاربر دیگری تغییر کرده است. صفحه را تازه‌سازی کنید.',
  WAREHOUSE_NOT_FOUND: 'انبار مورد نظر پیدا نشد.',
  WAREHOUSE_CODE_ALREADY_EXISTS: 'کد انبار در این شرکت تکراری است.',
  WAREHOUSE_INVALID_STATUS_TRANSITION: 'تغییر وضعیت انبار مجاز نیست.',
  WAREHOUSE_DEFAULT_CONFLICT: 'تعارض در انبار پیش‌فرض شرکت رخ داد. دوباره تلاش کنید.',
  WAREHOUSE_DEFAULT_REQUIRES_ACTIVE: 'فقط انبار فعال می‌تواند پیش‌فرض باشد.',
  WAREHOUSE_DEFAULT_REPLACEMENT_REQUIRED:
    'برای غیرفعال‌سازی انبار پیش‌فرض، باید انبار فعال دیگری را به‌عنوان پیش‌فرض انتخاب کنید.',
  WAREHOUSE_DEFAULT_REPLACEMENT_INVALID: 'انبار جایگزین پیش‌فرض نامعتبر است.',
  WAREHOUSE_HAS_ACTIVE_LOCATIONS:
    'تا وقتی مکان‌های فعال وجود دارند نمی‌توان انبار را غیرفعال کرد.',
  WAREHOUSE_LOCATION_NOT_FOUND: 'مکان انبار پیدا نشد.',
  WAREHOUSE_LOCATION_CODE_ALREADY_EXISTS: 'کد مکان در این انبار تکراری است.',
  WAREHOUSE_LOCATION_BARCODE_CONFLICT: 'تعارض در بارکد مکان. دوباره تلاش کنید.',
  WAREHOUSE_LOCATION_BARCODE_NOT_FOUND: 'بارکد مکان پیدا نشد.',
  WAREHOUSE_LOCATION_INVALID_PARENT: 'مکان والد باید در همان انبار باشد.',
  WAREHOUSE_LOCATION_CYCLE: 'این تغییر والد باعث حلقه در سلسله‌مراتب می‌شود.',
  WAREHOUSE_LOCATION_TYPE_INVERSION: 'ترتیب نوع مکان نامعتبر است (سلسله‌مراتب معکوس).',
  WAREHOUSE_LOCATION_ACTIVE_DESCENDANTS:
    'تا وقتی زیرمجموعه‌های فعال وجود دارند نمی‌توان این مکان را غیرفعال کرد.',
  WAREHOUSE_LOCATION_WAREHOUSE_INACTIVE: 'ایجاد/فعال‌سازی مکان زیر انبار غیرفعال مجاز نیست.',
  GOODS_RECEIPT_NOT_FOUND: 'رسید کالا پیدا نشد.',
  GOODS_RECEIPT_NOT_DRAFT: 'فقط پیش‌نویس رسید قابل ویرایش است.',
  GOODS_RECEIPT_POSTED_IMMUTABLE: 'رسید ثبت‌نهایی‌شده قابل ویرایش نیست.',
  GOODS_RECEIPT_EMPTY: 'برای ثبت نهایی حداقل یک قلم لازم است.',
  GOODS_RECEIPT_ITEM_DUPLICATE: 'این قلم سفارش قبلاً در رسید وجود دارد.',
  GOODS_RECEIPT_INVALID_QUANTITY: 'تعداد دریافت باید عدد صحیح مثبت باشد.',
  GOODS_RECEIPT_WAREHOUSE_INACTIVE: 'فقط انبار فعال برای دریافت مجاز است.',
  UNKNOWN_BARCODE: 'بارکد شناسایی نشد.',
  SKU_NOT_IN_PURCHASE_ORDER: 'این کالا در سفارش خرید وجود ندارد.',
  AMBIGUOUS_PO_ITEM: 'این SKU با بیش از یک قلم سفارش مطابقت دارد.',
  PO_ITEM_ALREADY_FULLY_RECEIVED: 'این قلم قبلاً به‌طور کامل دریافت شده است.',
  PO_ITEM_RECEIVING_CLOSED: 'دریافت این قلم بسته شده است (کسری بسته).',
  RECEIVING_QUANTITY_EXCEEDED: 'تعداد درخواستی از ظرفیت قابل افزودن به این پیش‌نویس بیشتر است.',
  GRN_NOT_DRAFT: 'اسکن فقط روی پیش‌نویس رسید مجاز است.',
  PURCHASE_ORDER_NOT_RECEIVABLE: 'این سفارش خرید برای دریافت آماده نیست.',
  PURCHASE_ORDER_CANCELLED: 'سفارش خرید لغو شده است.',
  PURCHASE_ORDER_ALREADY_RECEIVED: 'سفارش خرید قبلاً به‌طور کامل دریافت شده است.',
  PURCHASE_ORDER_OVER_RECEIPT_NOT_ALLOWED: 'دریافت بیش از مقدار سفارش مجاز نیست.',
};

export function mapBusinessError(
  error: unknown,
  fallback = 'عملیات با خطا مواجه شد.',
): string {
  if (!isApiClientError(error)) return fallback;
  if (error.code && BUSINESS_MESSAGES[error.code]) {
    return BUSINESS_MESSAGES[error.code];
  }
  return error.message || fallback;
}

export function formatRequestIdHint(requestId?: string | null): string | null {
  if (!requestId) return null;
  return `شناسه خطا: ${requestId}`;
}
